services:
  server:
    build: 
     context: .
     target : final
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=exe201c_v2;User ID=sa;Password=Tam@4545;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;Application Intent=ReadWrite;Multi Subnet Failover=False"
    ports:
      - 7979:8080
    networks:
      - mssql-network
      
networks:
  mssql-network:
    external: true
