// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DATA.Models;

public partial class MembershipPlan
{
    public int PlanId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public int DurationDays { get; set; }

    public string Features { get; set; }

    public virtual ICollection<MembershipPlanAssignment> MembershipPlanAssignments { get; set; } = new List<MembershipPlanAssignment>();
}