// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DATA.Models;

public partial class Post
{
    public int PostId { get; set; }

    public int? UserId { get; set; }

    public int? PostTypeId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public decimal? BudgetOrSalary { get; set; }

    public string Skills { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string ImgUrl { get; set; }

    public virtual PostType PostType { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual User User { get; set; }
}