// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DATA.Models;

public partial class Review
{
    public int ReviewId { get; set; }

    public int? PostId { get; set; }

    public int? ReviewerId { get; set; }

    public int? RevieweeId { get; set; }

    public int Rating { get; set; }

    public string Comment { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Post Post { get; set; }

    public virtual User Reviewee { get; set; }

    public virtual User Reviewer { get; set; }
}